name: tex_to_pdf

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
            sudo apt-get update -y \

            # Install the full version 
            sudo apt-get install texlive-full -y

    - name: Generate pdfs 
      run: |
            cd /home/runner/work/HPC_Docs/HPC_Docs/SBATCH_Documentation
            lualatex main.tex

    - name: Commit and push PDFs
      run: |
            git config --global user.name 'GitHub Actions'
            git config --global user.email 'actions@github.com'
            git add SBATCH_Documentation/*.pdf
            git commit -m "Update generated PDFs" || echo "No changes to commit"
            git push
